using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RandomNumberFileReaderClassLibrary
{
	/// <summary>
	/// class for performing file operations.
	/// </summary>
	public static class FileOps
	{
		/// <summary>
		/// read numbers from a file.
		/// </summary>
		/// <param name="fileName">name of file to be read.</param>
		/// <returns>list of numbers.</returns>
		public static string ReadNumbers(string fileName, out List<int> output)
		{
			List<int> numbers = new List<int>();
			StreamReader inputFile;

			try
			{
				inputFile = File.OpenText(fileName);
				// open file.

				do
				{
					numbers.Add(int.Parse(inputFile.ReadLine()));
					// read number from line and add to list.
					// Parse used instead of TryParse because file contains values
					// generated by code and can therefore be trusted.	

				} while (!inputFile.EndOfStream);
				// iter until reaching end of file. 

				inputFile.Close();
				// close file.

				output = numbers;
				// set output.

				return "FILE READ SUCCESSFULLY!";
				// return success confirmation.
			}
			catch (Exception ex)
			{
				output = numbers;
				return ex.Message;
				// return error msg and output empty list.
			}
		}
	}
}
